import Order from "../models/Order.js";
import User from "../models/User.js";
import stripe from "../config/stripe.js";

// Global variables
const currency = "usd";
const delivery_fee = 10;

// Place order with COD
const placeOrderCOD = async (req, res) => {
  try {
    const { userId } = req.user;
    const { items, amount, address } = req.body;

    if (!items || !amount || !address) {
      return res.status(400).json({
        success: false,
        message: "Please fill all the fields",
      });
    }

    const orderData = {
      userId,
      items,
      amount,
      address,
      paymentMethod: "COD",
    };

    const newOrder = await Order.create(orderData);

    await User.findByIdAndUpdate(userId, { cartData: {} });

    res.status(200).json({
      success: true,
      message: "Order placed successfully",
    });
  } catch (error) {
    console.log("Error in placeOrderCOD controller:", error.message);

    res.status(500).json({
      success: false,
      message: "Server error",
    });
  }
};

// Place order with stripe
const placeOrderStripe = async (req, res) => {
  try {
    const { userId } = req.user;
    const { items, amount, address } = req.body;
    const { origin } = req.headers;

    if (!items || !amount || !address) {
      return res.status(400).json({
        success: false,
        message: "Please fill all the fields",
      });
    }

    const orderData = {
      userId,
      items,
      amount,
      address,
      paymentMethod: "Stripe",
    };

    const newOrder = await Order.create(orderData);

    const line_items = items.map((item) => ({
      price_data: {
        currency,
        product_data: {
          name: item.name,
        },
        unit_amount: item.price * 100,
      },
      quantity: item.quantity,
    }));

    line_items.push({
      price_data: {
        currency,
        product_data: {
          name: "Delivery Fee",
        },
        unit_amount: delivery_fee * 100,
      },
      quantity: 1,
    });

    const session = await stripe.checkout.sessions.create({
      success_url: `${origin}/verify?session_id={CHECKOUT_SESSION_ID}`, // {CHECKOUT_SESSION_ID} is a placeholder for the actual session ID that will be generated by Stripe when the session is created
      cancel_url: `${origin}/cart`,
      line_items,
      mode: "payment",

      metadata: {
        orderId: newOrder._id.toString(),
      },
    });

    res.status(200).json({
      success: true,
      message: "Order placed successfully",
      session_url: session.url,
    });
  } catch (error) {
    console.log("Error in placeOrderStripe controller:", error.message);

    res.status(500).json({
      success: false,
      message: "Server error",
    });
  }
};

const verifyStripe = async (req, res) => {
  try {
    const { userId } = req.user;
    const { sessionId } = req.body;

    const session = await stripe.checkout.sessions.retrieve(sessionId);

    if (session.payment_status === "paid") {
      const orderId = session.metadata.orderId;

      await Order.findByIdAndUpdate(orderId, { payment: true });
      await User.findByIdAndUpdate(userId, { cartData: {} });

      res.status(200).json({
        success: true,
        message: "Order placed successfully",
      });
    } else {
      res.status(200).json({
        success: false,
        message: "Order not placed successfully",
      });
    }
  } catch (error) {
    console.log("Error in verifyStripe controller:", error.message);

    res.status(500).json({
      success: false,
      message: "Server error",
    });
  }
};

// Get all orders for admin panel
const getAllOrders = async (req, res) => {
  try {
    const orders = await Order.find();

    res.status(200).json({
      success: true,
      orders,
    });
  } catch (error) {
    console.log("Error in getAllOrders controller:", error.message);

    res.status(500).json({
      success: false,
      message: "Server error",
    });
  }
};

// Get all orders of a user
const getUserOrders = async (req, res) => {
  try {
    const { userId } = req.user;

    const orders = await Order.find({ userId });

    res.status(200).json({
      success: true,
      orders,
    });
  } catch (error) {
    console.log("Error in getUserOrders controller:", error.message);

    res.status(500).json({
      success: false,
      message: "Server error",
    });
  }
};

// Update order status from admin panel
const updateOrderStatus = async (req, res) => {
  try {
    const { orderId, status } = req.body;

    const order = await Order.findById(orderId);

    if (!order) {
      return res.status(404).json({
        success: false,
        message: "Order not found",
      });
    }

    await Order.findByIdAndUpdate(orderId, { status });

    res.status(200).json({
      success: true,
      message: "Order status updated successfully",
    });
  } catch (error) {
    console.log("Error in updateOrderStatus controller:", error.message);

    res.status(500).json({
      success: false,
      message: "Server error",
    });
  }
};

export {
  placeOrderCOD,
  placeOrderStripe,
  getAllOrders,
  getUserOrders,
  updateOrderStatus,
  verifyStripe,
};
